version: '3'

services:
  db:
    container_name: crud_nestjs_db
    image: postgres:13.3-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}      
    ports:
      - ${DATABASE_PORT}:5432